FROM node:22-alpine

WORKDIR /workspace

COPY package*.json ./
COPY backend/package*.json ./backend/
COPY frontend/package*.json ./frontend/
RUN npm install

COPY tsconfig.base.json ./tsconfig.base.json
COPY frontend ./frontend

EXPOSE 5173
CMD ["npm", "--workspace", "frontend", "run", "dev", "--", "--host", "0.0.0.0"]
