FROM node:22-alpine

WORKDIR /workspace

COPY package*.json ./
COPY backend/package*.json ./backend/
COPY frontend/package*.json ./frontend/
RUN npm install

COPY tsconfig.base.json ./tsconfig.base.json
COPY backend ./backend

EXPOSE 3000
CMD ["npm", "--workspace", "backend", "run", "start:dev"]
