/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a manual ingestion run */
        post: operations["createIngestionBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/batches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ingestion batch status */
        get: operations["getIngestionBatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/batches/{id}/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List row-level ingestion errors */
        get: operations["listIngestionBatchErrors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List normalized cost records */
        get: operations["listCostRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost-records/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get pre-aggregated cost totals */
        get: operations["getCostRecordsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost-records/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export normalized cost records as CSV */
        get: operations["exportCostRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cost-explorer/flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sankey-shaped cost explorer flow */
        get: operations["getCostExplorerFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenants available to the authenticated principal */
        get: operations["listTenants"];
        put?: never;
        /** Create a tenant shell */
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cloud-connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List read-only cloud account connections for the active tenant */
        get: operations["listCloudConnections"];
        put?: never;
        /** Register a read-only cloud connection reference */
        post: operations["createCloudConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cloud-connections/{id}/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate read-only cloud connection metadata */
        post: operations["validateCloudConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cloud-connections/{id}/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get provider-specific read-only onboarding policy templates */
        get: operations["getCloudConnectionOnboarding"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cloud billing accounts */
        get: operations["listAccounts"];
        put?: never;
        /** Create a cloud billing account reference */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List account groups */
        get: operations["listAccountGroups"];
        put?: never;
        /** Create an account group */
        post: operations["createAccountGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account-groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an account group */
        delete: operations["deleteAccountGroup"];
        options?: never;
        head?: never;
        /** Update an account group */
        patch: operations["updateAccountGroup"];
        trace?: never;
    };
    "/cloud-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cloud credential Vault references */
        get: operations["listCloudCredentials"];
        put?: never;
        /** Register a cloud credential Vault reference */
        post: operations["createCloudCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cloud-credentials/{id}/rotation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rotate a cloud credential Vault reference */
        patch: operations["rotateCloudCredential"];
        trace?: never;
    };
    "/dimensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List custom dimensions */
        get: operations["listDimensions"];
        put?: never;
        /** Create an unbounded custom dimension */
        post: operations["createDimension"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dimensions/{id}/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a tag mapping to a dimension */
        post: operations["createDimensionMapping"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resource-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags for a resource */
        get: operations["listResourceTags"];
        put?: never;
        /** Upsert a manual or inferred resource tag */
        post: operations["upsertResourceTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List optimization recommendations */
        get: operations["listRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update recommendation status */
        patch: operations["updateRecommendation"];
        trace?: never;
    };
    "/realized-savings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List realized savings ledger rows */
        get: operations["listRealizedSavings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List canned reports */
        get: operations["listReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run a canned report */
        get: operations["runReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved views */
        get: operations["listViews"];
        put?: never;
        /** Create a saved view */
        post: operations["createView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executive-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get executive spend summary */
        get: operations["getExecutiveSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executive-summary/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export executive spend summary as PDF */
        get: operations["exportExecutiveSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tco/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimate cross-cloud cost for a workload */
        post: operations["estimateTco"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        /** Create user */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles */
        get: operations["listRoles"];
        put?: never;
        /** Reject custom role creation until the custom-role milestone */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable audit log entries */
        get: operations["listAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /**
             * Format: uri
             * @example https://api.costalyx.local/errors/validation-error
             */
            type: string;
            /** @example Validation Error */
            title: string;
            status: number;
            detail: string;
            instance: string;
            requestId?: string;
            errors?: {
                [key: string]: unknown;
            }[];
        };
        HealthStatus: {
            /** @enum {string} */
            status: "ok";
        };
        /** @enum {string} */
        CloudProvider: "aws" | "azure" | "gcp";
        /** @enum {string} */
        LeaseType: "on_demand" | "reserved" | "savings_plan" | "spot";
        /** @enum {string} */
        RoleName: "viewer" | "analyst" | "admin";
        Tenant: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** @enum {string} */
            plan: "starter" | "business" | "enterprise";
            /** Format: date-time */
            createdAt: string;
        };
        TenantCreate: {
            name: string;
            slug?: string;
            /** @enum {string} */
            plan?: "starter" | "business" | "enterprise";
        };
        CloudConnection: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** @description Costalyx-generated external ID that the customer configures in their AWS role trust policy. Not a secret. */
            externalId: string;
            provider: components["schemas"]["CloudProvider"];
            displayName: string;
            /** @description AWS account ID, Azure tenant/billing scope ID, or GCP billing account/project parent. */
            externalTenantId: string;
            /** @enum {string} */
            accessMode: "aws_assume_role" | "azure_delegated_app" | "gcp_workload_identity";
            /** @description Role ARN, delegated app ID, or workload identity provider reference. Never a secret. */
            readOnlyPrincipal: string;
            /** @description Billing export location only. Signed URLs, SAS tokens, access tokens, query credentials, and embedded secrets are rejected. */
            billingExportUri: string | null;
            /** @enum {string} */
            status: "pending_validation" | "ready_for_live_probe" | "validated" | "validation_failed";
            /** Format: date-time */
            lastValidatedAt: string | null;
            /** Format: date-time */
            lastValidationAttemptedAt: string | null;
            /** @enum {string|null} */
            lastValidationCode: "shape_invalid" | "provider_probe_not_implemented" | "live_probes_disabled" | "aws_billing_export_required" | "aws_account_mismatch" | "aws_billing_export_empty" | "aws_probe_failed" | "aws_probe_passed" | "azure_billing_export_required" | "azure_billing_export_empty" | "azure_probe_failed" | "azure_probe_passed" | "gcp_billing_export_required" | "gcp_billing_export_empty" | "gcp_probe_failed" | "gcp_probe_passed" | null;
            lastValidationMessage: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        CloudConnectionCreate: {
            provider: components["schemas"]["CloudProvider"];
            displayName: string;
            externalTenantId: string;
            /** @enum {string} */
            accessMode: "aws_assume_role" | "azure_delegated_app" | "gcp_workload_identity";
            /** @description Read-only delegated principal reference only. Access keys, client secrets, service-account JSON, and base64 credential blobs are rejected. */
            readOnlyPrincipal: string;
            /** @description Unsigned billing export location. Do not submit presigned URLs, SAS URLs, access tokens, or credential-bearing query strings. */
            billingExportUri?: string;
        };
        CloudConnectionOnboarding: {
            provider: components["schemas"]["CloudProvider"];
            /** Format: uuid */
            connectionId: string;
            /** @description Costalyx-generated external ID used in the customer trust policy. Not a secret. */
            externalId: string;
            /**
             * @description Readiness of provider-specific onboarding templates. Azure and GCP templates use `ready` when role/IAM guidance can be generated.
             * @enum {string}
             */
            status: "ready" | "broker_principal_missing" | "broker_principal_invalid" | "billing_export_missing" | "provider_not_implemented";
            brokerPrincipalArn: string | null;
            billingExportUri: string | null;
            trustPolicy: {
                [key: string]: unknown;
            } | null;
            /** @description Provider-specific readonly permission template: AWS IAM policy, Azure role assignment guidance, or GCP IAM binding guidance. */
            permissionsPolicy: {
                [key: string]: unknown;
            } | null;
            customerSteps: string[];
        };
        /** @example 1234.5600 */
        MoneyString: string;
        ListMeta: {
            total: number;
            page: number;
            pageSize: number;
        };
        Account: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            provider: components["schemas"]["CloudProvider"];
            /** Format: uuid */
            cloudConnectionId: string | null;
            externalAccountId: string;
            displayName: string;
            vendor: string;
            /** Format: date-time */
            createdAt: string;
        };
        AccountCreate: {
            provider: components["schemas"]["CloudProvider"];
            externalAccountId: string;
            displayName: string;
            /** Format: uuid */
            cloudConnectionId?: string;
            /** @description Vault/OpenBao path reference only; never a plaintext secret. */
            vaultCredentialPath?: string;
        };
        AccountGroup: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            name: string;
            accountIds: string[];
            /** Format: date-time */
            createdAt: string;
        };
        AccountGroupCreate: {
            name: string;
            accountIds: string[];
        };
        AccountGroupPatch: {
            name?: string;
            accountIds?: string[];
        };
        CloudCredential: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            provider: components["schemas"]["CloudProvider"];
            /** Format: uuid */
            accountId: string;
            displayName: string;
            /** @description Vault/OpenBao path reference only; never a plaintext or base64 credential. */
            vaultPath: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            rotatedAt: string | null;
        };
        CloudCredentialCreate: {
            provider: components["schemas"]["CloudProvider"];
            /** Format: uuid */
            accountId: string;
            displayName: string;
            /** @description Vault/OpenBao path reference only; plaintext credential fields are rejected. */
            vaultPath: string;
        };
        CloudCredentialRotation: {
            /** @description New Vault/OpenBao path reference only. */
            vaultPath: string;
        };
        CostRecord: {
            /** Format: uuid */
            id: string;
            provider: components["schemas"]["CloudProvider"];
            /** Format: uuid */
            accountId: string;
            resourceId: string;
            serviceName: string;
            usageFamily?: string;
            leaseType: components["schemas"]["LeaseType"];
            transactionType?: string;
            hourlyRateUsd: components["schemas"]["MoneyString"];
            usageHours: string;
            /** @description Computed at query time, never stored. */
            readonly costTotalUsd: components["schemas"]["MoneyString"];
            isEstimate: boolean;
            /** Format: date-time */
            validFrom: string;
            /** Format: date-time */
            validTo?: string | null;
            /** Format: date-time */
            ingestedAt?: string;
        };
        CostSummary: {
            totalCostUsd: components["schemas"]["MoneyString"];
            resourceCount: number;
            untaggedCount: number;
            inactiveCount: number;
            isEstimate: boolean;
        };
        CostExplorerFlow: {
            nodes: {
                id: string;
                label: string;
                costTotalUsd: components["schemas"]["MoneyString"];
            }[];
            links: {
                source: string;
                target: string;
                costTotalUsd: components["schemas"]["MoneyString"];
            }[];
        };
        Dimension: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orgId: string;
            name: string;
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
        };
        DimensionCreate: {
            name: string;
        };
        DimensionMapping: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            dimensionId: string;
            tagKey: string;
            tagValuePattern?: string | null;
        };
        DimensionMappingCreate: {
            tagKey: string;
            tagValuePattern?: string | null;
        };
        ResourceTag: {
            resourceId: string;
            tagKey: string;
            tagValue: string;
            /** @enum {string} */
            source: "native" | "manual" | "inferred";
        };
        ResourceTagUpsert: {
            resourceId: string;
            tagKey: string;
            tagValue: string;
            /** @enum {string} */
            source: "native" | "manual" | "inferred";
        };
        IngestionBatch: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId?: string;
            provider: components["schemas"]["CloudProvider"];
            /** @enum {string} */
            status: "pending" | "processing" | "complete" | "failed";
            /** Format: uuid */
            cloudConnectionId?: string | null;
            sourceUri?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string | null;
            ingestedRows: number;
            duplicateRows: number;
        };
        IngestionBatchCreate: {
            provider: components["schemas"]["CloudProvider"];
            /** @description Provider-native source URI or object reference. */
            sourceUri: string;
            /** Format: uuid */
            cloudConnectionId?: string;
        };
        IngestionError: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            batchId: string;
            rowNumber: number;
            detail: string;
        };
        /** @enum {string} */
        RecommendationStatus: "open" | "applied" | "dismissed";
        Recommendation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId?: string;
            /** @enum {string} */
            type: "rightsizing" | "ri_purchase" | "idle" | "commitment_gap";
            resourceId: string;
            estimatedSavingsUsd: components["schemas"]["MoneyString"];
            status: components["schemas"]["RecommendationStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        RecommendationPatch: {
            /** @enum {string} */
            status: "applied" | "dismissed";
        };
        RealizedSaving: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            recommendationId: string;
            /** Format: date-time */
            appliedAt: string;
            baselineCostUsd: components["schemas"]["MoneyString"];
            actualCostUsd: components["schemas"]["MoneyString"];
            deltaUsd: components["schemas"]["MoneyString"];
            /** @enum {string} */
            verificationSource: "ingested_billing";
        };
        /** @enum {string} */
        ReportCategory: "cost" | "cost_summary" | "invoices" | "utilization" | "underutilization";
        Report: {
            /** Format: uuid */
            id: string;
            name: string;
            category: components["schemas"]["ReportCategory"];
            description?: string;
        };
        ReportRun: {
            /** Format: uuid */
            reportId: string;
            /** Format: date-time */
            generatedAt: string;
            rows: {
                [key: string]: unknown;
            }[];
        };
        View: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orgId: string;
            name: string;
            filterJson: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            ownerId: string;
            sharedRoleScope: components["schemas"]["RoleName"][];
        };
        ViewCreate: {
            name: string;
            filterJson: {
                [key: string]: unknown;
            };
            sharedRoleScope?: components["schemas"]["RoleName"][];
        };
        ExecutiveSummary: {
            totalSpendUsd: components["schemas"]["MoneyString"];
            revenueBaselineUsd: components["schemas"]["MoneyString"];
            spendAsRevenuePercent: string;
            budgetBaselineUsd: components["schemas"]["MoneyString"];
            budgetUsedPercent: string;
            trend: components["schemas"]["ExecutiveTrend"];
            topMovers: components["schemas"]["ExecutiveTopMover"][];
        };
        ExecutiveTrend: {
            /** @enum {string} */
            direction: "up" | "down" | "flat";
            deltaUsd: components["schemas"]["MoneyString"];
        };
        ExecutiveTopMover: {
            resourceId: string;
            serviceName: string;
            deltaUsd: components["schemas"]["MoneyString"];
        };
        TcoEstimateRequest: {
            workloadSpec: {
                [key: string]: unknown;
            };
        };
        TcoEstimateResponse: {
            aws: components["schemas"]["TcoProviderEstimate"];
            azure: components["schemas"]["TcoProviderEstimate"];
            gcp: components["schemas"]["TcoProviderEstimate"];
            tolerancePercent: string;
        };
        TcoProviderEstimate: {
            monthlyCostUsd: components["schemas"]["MoneyString"];
            isEstimate: boolean;
            assumptions?: string[];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: email */
            email: string;
            displayName: string;
            roles: components["schemas"]["RoleName"][];
        };
        UserCreate: {
            /** Format: email */
            email: string;
            displayName: string;
            roles: components["schemas"]["RoleName"][];
        };
        Role: {
            name: components["schemas"]["RoleName"];
            fixed: boolean;
        };
        RoleCreate: {
            name: string;
            /** @description Future additive custom-role permission bitset. */
            permissionBitset?: string;
        };
        AuditLogEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            actorId: string;
            action: string;
            targetType: string;
            targetId: string;
            prevHash: string | null;
            hash: string;
            /** Format: date-time */
            createdAt: string;
        };
        PaginatedCostRecords: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["CostRecord"][];
        };
        PaginatedAccounts: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["Account"][];
        };
        PaginatedAccountGroups: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["AccountGroup"][];
        };
        PaginatedCloudConnections: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["CloudConnection"][];
        };
        PaginatedCloudCredentials: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["CloudCredential"][];
        };
        PaginatedDimensions: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["Dimension"][];
        };
        PaginatedResourceTags: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["ResourceTag"][];
        };
        PaginatedIngestionErrors: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["IngestionError"][];
        };
        PaginatedRecommendations: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["Recommendation"][];
        };
        PaginatedRealizedSavings: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["RealizedSaving"][];
        };
        PaginatedReports: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["Report"][];
        };
        PaginatedViews: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["View"][];
        };
        PaginatedUsers: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["User"][];
        };
        PaginatedAuditLog: components["schemas"]["PaginatedResponse"] & {
            data?: components["schemas"]["AuditLogEntry"][];
        };
        PaginatedResponse: {
            data: unknown[];
            meta: components["schemas"]["ListMeta"];
        };
    };
    responses: {
        /** @description Request validation failed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid bearer token */
        Unauthorized: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated caller lacks the required role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Request conflicts with current state or idempotency replay */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Unexpected server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Id: string;
        /** @description Required on every mutating request; duplicate keys return the original result. */
        IdempotencyKey: string;
        /** @description Optional saved View applied as a session-wide data scope. */
        ActiveViewId: string;
        Page: number;
        PageSize: number;
        Provider: components["schemas"]["CloudProvider"];
        DateFrom: string;
        DateTo: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus-compatible metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createIngestionBatch: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionBatchCreate"];
            };
        };
        responses: {
            /** @description Ingestion batch accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionBatch"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getIngestionBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingestion batch status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionBatch"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listIngestionBatchErrors: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated ingestion errors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIngestionErrors"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCostRecords: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                provider?: components["parameters"]["Provider"];
                accountId?: string;
                accountGroupId?: string;
                cloudConnectionId?: string;
                service?: string;
                from?: components["parameters"]["DateFrom"];
                to?: components["parameters"]["DateTo"];
                dimension?: string;
            };
            header?: {
                /** @description Optional saved View applied as a session-wide data scope. */
                "X-Costalyx-View-Id"?: components["parameters"]["ActiveViewId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated cost records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCostRecords"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getCostRecordsSummary: {
        parameters: {
            query?: {
                provider?: components["parameters"]["Provider"];
                accountId?: string;
                accountGroupId?: string;
                cloudConnectionId?: string;
                from?: components["parameters"]["DateFrom"];
                to?: components["parameters"]["DateTo"];
                dimension?: string;
            };
            header?: {
                /** @description Optional saved View applied as a session-wide data scope. */
                "X-Costalyx-View-Id"?: components["parameters"]["ActiveViewId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cost summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    exportCostRecords: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional saved View applied as a session-wide data scope. */
                "X-Costalyx-View-Id"?: components["parameters"]["ActiveViewId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV export of normalized cost records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getCostExplorerFlow: {
        parameters: {
            query?: {
                provider?: components["parameters"]["Provider"];
                accountId?: string;
                accountGroupId?: string;
                cloudConnectionId?: string;
                from?: components["parameters"]["DateFrom"];
                to?: components["parameters"]["DateTo"];
                /** @description Ordered dimensions to drill through */
                dimensions?: string[];
                costFloorUsd?: components["schemas"]["MoneyString"];
            };
            header?: {
                /** @description Optional saved View applied as a session-wide data scope. */
                "X-Costalyx-View-Id"?: components["parameters"]["ActiveViewId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sankey flow graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostExplorerFlow"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant memberships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Tenant"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantCreate"];
            };
        };
        responses: {
            /** @description Tenant created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listCloudConnections: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated cloud connections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCloudConnections"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createCloudConnection: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloudConnectionCreate"];
            };
        };
        responses: {
            /** @description Cloud connection registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudConnection"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    validateCloudConnection: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cloud connection validation result */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudConnection"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getCloudConnectionOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cloud connection onboarding template */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudConnectionOnboarding"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                provider?: components["parameters"]["Provider"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccounts"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Account created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listAccountGroups: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated account groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccountGroups"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAccountGroup: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountGroupCreate"];
            };
        };
        responses: {
            /** @description Account group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountGroup"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteAccountGroup: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account group deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAccountGroup: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountGroupPatch"];
            };
        };
        responses: {
            /** @description Account group updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountGroup"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCloudCredentials: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated credential references */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCloudCredentials"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createCloudCredential: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloudCredentialCreate"];
            };
        };
        responses: {
            /** @description Credential reference registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudCredential"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    rotateCloudCredential: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloudCredentialRotation"];
            };
        };
        responses: {
            /** @description Credential reference rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudCredential"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listDimensions: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated dimensions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDimensions"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createDimension: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DimensionCreate"];
            };
        };
        responses: {
            /** @description Dimension created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dimension"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    createDimensionMapping: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DimensionMappingCreate"];
            };
        };
        responses: {
            /** @description Dimension mapping created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DimensionMapping"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listResourceTags: {
        parameters: {
            query: {
                resourceId: string;
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated resource tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResourceTags"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    upsertResourceTag: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceTagUpsert"];
            };
        };
        responses: {
            /** @description Resource tag upserted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceTag"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listRecommendations: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                status?: components["schemas"]["RecommendationStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated recommendations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecommendations"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateRecommendation: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationPatch"];
            };
        };
        responses: {
            /** @description Recommendation updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recommendation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRealizedSavings: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated realized savings rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRealizedSavings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listReports: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                category?: components["schemas"]["ReportCategory"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated report catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedReports"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    runReport: {
        parameters: {
            query?: {
                provider?: components["parameters"]["Provider"];
                accountId?: string;
                accountGroupId?: string;
                cloudConnectionId?: string;
                from?: components["parameters"]["DateFrom"];
                to?: components["parameters"]["DateTo"];
            };
            header?: {
                /** @description Optional saved View applied as a session-wide data scope. */
                "X-Costalyx-View-Id"?: components["parameters"]["ActiveViewId"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Report result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRun"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listViews: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated views */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedViews"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createView: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewCreate"];
            };
        };
        responses: {
            /** @description View created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getExecutiveSummary: {
        parameters: {
            query?: {
                revenueBaselineUsd?: components["schemas"]["MoneyString"];
                budgetBaselineUsd?: components["schemas"]["MoneyString"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Executive spend summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutiveSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    exportExecutiveSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Executive summary PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    estimateTco: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TcoEstimateRequest"];
            };
        };
        responses: {
            /** @description Cross-cloud TCO estimate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TcoEstimateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUsers"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description User created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Role"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on every mutating request; duplicate keys return the original result. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleCreate"];
            };
        };
        responses: {
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listAuditLog: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated audit log entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAuditLog"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
