{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "costalyx.fullname" . }}-default-deny
  labels:
    {{- include "costalyx.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "costalyx.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "costalyx.fullname" . }}-allow-app-traffic
  labels:
    {{- include "costalyx.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "costalyx.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.ingressController.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.ingressController.podSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 8080
  egress:
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 8200
        - protocol: TCP
          port: 9092
{{- end }}
